---

- name: restaura o diret√≥rio .ApacheDirectoryStudio
  ansible.builtin.copy:
    src: '{{path_to_backup}}/home/{{user.login}}/.ApacheDirectoryStudio/'
    dest: '/home/{{user.login}}/.ApacheDirectoryStudio/'
    local_follow: false
    mode: preserve
    owner: '{{user.login}}'
    group: '{{user.group}}'

...